### ISSUE TITLE
Integrate Hanzi Helper functionality

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#107]
In the past, I've used Hanzi Helper to learn Chinese. Do you think it's possible to integrate some of its functionality such as the ability to create and print vocabulary lists and character sheets? http://hanzihelper.sourceforge.net/

**Comment by sotch-pr35mac** [comment]
I definitely think this is a feature that could be incorporated in one of the upcoming releases. But I'm not super clear on what format vocabulary lists would print in. Would they print to look like a spreadsheet style grid of the character in Traditional, Simplified, pinyin, and then also include some definitions?

I'm attaching some screenshots to this issue for reference: 

![Character Sheets](http://hanzihelper.sourceforge.net/screen2.jpg)

![Vocabulary Lists](http://hanzihelper.sourceforge.net/new_screen1.jpg)

**Comment by baimafeima** [comment]
What I liked about Hanzi Helper is the idea that you could key in all new characters into a comprehensive list. What was missing is the distinction between traditional and simplified characters. This list could then be exported to various (now out-dated) vocabulary learning programs. But perhaps the greatest virtue of Hanzi Helper was its focus on a few select functions. Now there are great programs such Anki or the Mnemosyne Project - both are spaced repetition programs/electronic flash card programs - which could be used in conjunction with either an updated Hanzi Helper or with Syng if such functionality were integrated. 

The second functionality, the printable character sheets, aims at a different learning style. Especially when it comes to active writing, using a spaced repetition program is not enough. Up to this day, there are only various proprietary web-based solutions which offer this functionality.

**Comment by sotch-pr35mac** [comment]
I’m a little confused about the first part, what would the feature to be added be? Syng already has support for user defined vocabulary lists and flash cards (ailbeit not as fancy as Anki but gets the job done). These lists are also exportable as JSON files.

**Comment by sotch-pr35mac** [comment]
Clearing out tasks that are no longer relevant.
