### ISSUE TITLE
Blog

### ISSUE THREAD

**Issue by sotch-pr35mac** [sotch-pr35mac/syng#121]
Build a blog to talk about some of the new features of Syng, the reasons behind making certain decisions with the project, and for overall better communication with the user base.

**Comment by baimafeima** [comment]
That's a great idea! As the user base grows (and perhaps developers or other contributors are recruited) it would also make sense to have an official IRC channel where users help each other and issues regarding development and more generally regarding Chinese language learning can be discussed. I'd be happy to join your project.

**Comment by sotch-pr35mac** [comment]
@baimafeima Yeah that sounds like a great idea! That's definitely something I am going to setup as Syng moves into Phase 2.

**Comment by sotch-pr35mac** [comment]
Will revisit this after the development of v2.
