### ISSUE TITLE
Create AppImage

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#127]
Similar to `exe` and `dmg` files, `AppImages` are designed to be executed directly on a user's computer, however without any installation needed. It would provide the easiest way to get Syng running on a Linux-based operating system without having to build it from source. It would be great to get this to work for the next release: https://appimage.org/

**Comment by sotch-pr35mac** [comment]
With the latest beta release for v2, AppImages are now part of the build process.
