### ISSUE TITLE
"Report bug" screen shows "Network connection required"

### ISSUE THREAD

**Issue by IdiosApps** [sotch-pr35mac/syng#128]
![image](https://user-images.githubusercontent.com/12559216/80519896-9b260200-8980-11ea-8ab5-08dc8fddbdb9.png)

Not sure how network detection is done, but I am indeed connected to the internet.

After restart the message still shows.

**Comment by IdiosApps** [comment]
V. low priority, just adding it here as it wasn't an existing issue.

**Comment by sotch-pr35mac** [comment]
Sorry for the late reply on this one, I haven't been maintaining this project. The network requirement notice will actually be present regardless of network status, so this is indeed expected behavior. 

Thank you!
