### ISSUE TITLE
Download link on main website points to 1.2.0

### ISSUE THREAD

**Issue by JaJaWa** [sotch-pr35mac/syng#142]
The download link on the main website points to 1.2.0 (for the macOS version at least)

**Comment by sotch-pr35mac** [comment]
Thanks for pointing this out. I haven't updated the website and this has slipped my mind. I also haven't built a release for all systems in a minute, which might be why some of the other links have been outdated. I'll make sure to get this updated when I refresh some of the website.

**Comment by sotch-pr35mac** [comment]
This has been resolved and the website now points to the most recent available installation candidate for each platform.
