### ISSUE TITLE
Setting for custom tone colours?

### ISSUE THREAD

**Issue by bengb** [sotch-pr35mac/syng#146]
Could you add a setting to change the tone colours?

I have used different colours to indicate tones for many years in other apps (e.g. Pleco), so it would be great if I can adjust the colours in Syng to match what I am used to.

Thanks!

**Comment by sotch-pr35mac** [comment]
Yes this is something I was planning on working into a larger update, but given how practical it is I will get something put together to handle this in the current version so the feature can be used right away. Won't be beautiful but should get the job done. 

Thanks for reaching out with this feature request!

**Comment by sotch-pr35mac** [comment]
[Here's the latest Syng release for macOS (v1.5.0)](https://github.com/sotch-pr35mac/syng/releases/download/v1.5.0/Syng-macOS.dmg). 

Do let me know if you use a different system than macOS. I could only build the binary for Mac right now, but I could spin of a virtual machine to cut other binaries if needed.

**Comment by bengb** [comment]
Just gave a try...it works great!
Thanks again for doing this so quickly!
