### ISSUE TITLE
MacOs - importing Words

### ISSUE THREAD

**Issue by johans3** [sotch-pr35mac/syng#152]
Hello,
sorry the dumb question but what files are supported to import vocabulary? there is no info under help what files are supported.
*.txt or *csv should be fine, but they are grayed out, cannot select-import these.

Also, if i cancel my import in the file chooser, because i cannot select any file, Syng throws an error.

**Comment by sotch-pr35mac** [comment]
Hi @johans3, thank you for reaching out. You can only import files exported from Syng. When you export a file you'll get a `.sld` file that can be imported. What are you trying to import from / what is the source of the words you'd like to import? 

--- 

Thank you for bringing up the error, I'll check it out.
