### ISSUE TITLE
Windows version outdated (v1.2.0 from site)

### ISSUE THREAD

**Issue by IdiosApps** [sotch-pr35mac/syng#194]
Downloading https://github.com/sotch-pr35mac/syng/releases/download/v1.2.0/Syng-Windows-setup-x64.exe from https://www.getsyng.com/home#download gives version 1.2.0.

What does your process look like for making a release for different OSes?
Maybe I can help with GitHub Actions to generate artefacts on tag.

**Comment by sotch-pr35mac** [comment]
For v1 my release and packaging processes were very ad-hoc. I used [electron-packager](https://github.com/electron/electron-packager) to package releases for any given system, but I haven't run it in so long I can't quite remember exactly what to do. The gist of it would be:
1. Clone the repo
2. Checkout the release you want to build (the latest stable is `v1.5.0`)
3. Run electron packager by following the instructions provided from them. I can provide any assets if you need them (like a icon or the like).

Related to this, work on v2 is on-going, and I'm currently working on migrating the beta from Electron to Tauri. As part of that transition I'll be adding CI to build and package releases including for Windows.
