### ISSUE TITLE
Handwriting Recognition

### ISSUE THREAD

**Issue by sotch-pr35mac** [sotch-pr35mac/syng#35]
A feature to be able to lookup characters by drawing them into Syng and having it turn them into characters.

**Comment by baimafeima** [comment]
Did you write the handwriting component from scratch or is it based on any other project?

**Comment by sotch-pr35mac** [comment]
I haven't written the handwriting recognition yet. I am *hoping* there is already a library I can use, but I haven't done any serious research on the topic as of yet as this feature is marked for v0.5.0.

**Comment by sotch-pr35mac** [comment]
Things that might be helpful when writing this: 
1. [Tesseract.js](http://tesseract.projectnaptha.com/)
2. [minhmt's html5-handwriting repository](https://github.com/minhmt/html5-handwriting)

**Comment by sotch-pr35mac** [comment]
Moving on-hold issues into the roadmap.

**Comment by sotch-pr35mac** [comment]
Re-opening this issue and adding it to the Phase 4 Project.

**Comment by sotch-pr35mac** [comment]
Clearing out tasks that are no longer relevant.
