### ISSUE TITLE
Packaged Installer

### ISSUE THREAD

**Issue by sotch-pr35mac** [sotch-pr35mac/syng#41]
Create an installer package so the application contents don't just sit in an in archived folder. 
### OS X
- Create either a folder with a shortcut to the Applications folder, or create a `.pkg` file that will get install Syng.
- Add to the release notes that they must enable install from unregistered developers.
### Linux
- For Debian based distros have a `.deb`
- For Ubuntu 16.04+ use `.snappy`
- For all other distros continue using the `install.sh` script
### Windows
- Create `.msi` installer using [AdvancedInstaller](http://www.advancedinstaller.com/)

**Comment by sotch-pr35mac** [comment]
All but the `.snap` package for Ubuntu 16.04+ and the `.msi` for Windows have been built. Currently working on the `.snap` for Linux, but have no good way of packaging for Windows seeing as I don't have a Windows computer available at my disposal.

**Comment by sotch-pr35mac** [comment]
Still having an issue uploading the binary for Windows 32-bit. Still haven't built the .snap package yet.

**Comment by sotch-pr35mac** [comment]
Closing this issue in favor of a Github project to get Syng onto more app distribution platforms.

**Comment by baimafeima** [comment]
I think it doesn't make sense to build a .snap package when you already have a .deb package. Would be duplicate effort. On the other side, if you were to drop offering .deb packages, a .snap package seems to be the better idea.
