### ISSUE TITLE
MacOS Testing Closing All Windows

### ISSUE THREAD

**Issue by steventhanna** [sotch-pr35mac/syng#44]
Attempted to close the main window while no other windows were open, and received the following error: 

```
Uncaught Exception:
TypeError: Cannot read property 'close' of null at BrowserWindow.<anonymous>
... main.js61:10
```

<img width="1062" alt="screen shot 2016-07-31 at 9 30 59 am" src="https://cloud.githubusercontent.com/assets/2541678/17277171/ceecaafe-5701-11e6-8f4a-4072545a3df1.png">

**Comment by sotch-pr35mac** [comment]
@steventhanna How long after the application had loaded did you attempt to close it and receive the error?

The line that is causing you issue is `lgChars.close();` where `lgChars` is a BrowserWindow object that gets initialized on line `228`. If it is the case line `228` doesn't get run by the time you attempt to close the main window, then `lgChars` will be `undefined` and throw an error.

**Comment by steventhanna** [comment]
Maybe 30 seconds after the windows were loaded I attempted to close.

**Comment by sotch-pr35mac** [comment]
@steventhanna Was this an isolated issue or is it recreatable?

**Comment by steventhanna** [comment]
Recreatable.  If I have time, I will propose a fix

**Comment by sotch-pr35mac** [comment]
pull request was pulled and merged.
