### ISSUE TITLE
Integrate character animations via hanzi-writer

### ISSUE THREAD

**Issue by baimafeima** [sotch-pr35mac/syng#90]
I recently talked to @chanind, developer of `hanzi-writer` and he had this to say: 

> I don't plan on building any applications for Hanzi-writer - I'm just focused on making the library itself better. Other developers can take Hanzi-writer and make desktop or other applications with it. It's all free and open source so I hope others will take it and build innovative applications for Chinese learning.

What do you think?

Repository: https://github.com/chanind/hanzi-writer
Character animation/Homepage: https://chanind.github.io/hanzi-writer/
Desktop application use: https://github.com/chanind/hanzi-writer/issues/23

**Comment by sotch-pr35mac** [comment]
I have been wanting to add this feature for a long time, and this is a great repo! Thank you for sending it my way, this can definitely be implemented.

**Comment by sotch-pr35mac** [comment]
This feature has been added in the latest commit on the `develop` branch.
